name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=23.0.0
  - mlflow=2.2.2
  - hydra-core=1.0.6
  - wandb=0.14.0
  - pip:
      - hydra-joblib-launcher==1.1.2
