name: evaluate
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3
  - scikit-learn=0.24.1
  - matplotlib==3.2.2
  - plotly==4.4.1
  - pillow=8.1.2
  - mlflow=2.2.2
  - wandb=0.14.0
